proxies:
  - name: "MyRealityNode"
    type: vless
    server: 148.135.64.233
    port: 443
    uuid: 3cf397a9-dcdd-4a6d-b22b-3984abac869e
    network: tcp
    tls: true
    sni: www.unlv.edu
    servername: www.unlv.edu
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: 5LjH2JFdWa1XosfNBu_L-Byb8bX7OR52CG-m8yttlzU
      short-id: 0123456789abcdef
    skip-cert-verify: false 
